name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: sudo apt-get install libunistring-dev
        if: runner.os == 'Linux'
      - run: ./gradlew ciTests publish -PpublishCommonTargets=$PUBLISH_COMMON_TARGETS
        env:
          PUBLISH_COMMON_TARGETS: ${{ runner.os == 'Linux' }}
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        shell: bash
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        if: runner.os == 'Linux'
